### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by elliots** [wacul/ptr#2]
I know it seems silly, but would you mind putting a license on the project? 

We have tool with a fantastic name ( https://github.com/frapposelli/wwhrd ) that makes sure we don't use anything we aren't allowed to use, and this is a dependency of a dependency.

(I'd have created a pull-request for MIT but I don't know what the copyright message would be).

Cheers :)
E.

**Comment by kyoh86** [comment]
I've put the MIT license on this project.
Thank you for your cool proposal!

**Comment by kyoh86** [comment]
I've put the MIT license on this project.
Thank you for your cool proposal!
@elliots
